export const SETLOCALSTREAM = 'SETLOCALSTREAM';
export const SETREMOTESTREAM = 'SETREMOTESTREAM';
export const HANGUP = 'HANGUP';
export const SETPEERCONNECTION = 'SETPEERCONNECTION';
export const SETROOM = 'SETROOM';
export const SETINVITED = 'SETINVITED';